version: '3.8'

services:
  app:
    image: ibhoomika2/banking:latest
    container_name: banking-app
    depends_on:
      - db
    ports:
      - "8084:8081"  # Host:Container
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: bankingdb
      DB_USER: root
      DB_PASSWORD: root

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: bankingdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
